# Generated by Django 2.1.7 on 2019-03-13 18:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2019, 3, 13, 18, 1, 52, 935835))], verbose_name='Ending Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2019, 3, 13, 18, 1, 52, 935793))], verbose_name='Starting Time'),
        ),
    ]
