# Generated by Django 2.1.7 on 2019-03-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190313_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
